### ISSUE TITLE
Is IncBin prior art?

### ISSUE THREAD

**Issue by bryceschober** [ThePhD/embed#1]
Have you run across @graphitemaster's [incbin](https://github.com/graphitemaster/incbin) project? I use it in production, even though its interface is super-ugly C. At least it works across many compilers and platforms at assembly time, not a pre-compilation generator... though it falls far short of your ultimate goal of being compile-time constexpr.

That said, if I had something like your proposed std::embed interface to put in front of it, I'd get excited.

**Comment by ThePhD** [comment]
I've now listed `incbin` as part of the prior art.

Thanks for telling me about it.
